name: seelab
channels:
  - conda-forge
  - pytorch
  - anaconda
dependencies:
  - python=3.8
  - numpy
  - pandas
  - matplotlib
  - cython
  - pillow
  - pytorch=1.7
  - torchvision
  - cudatoolkit=10.2
  - scikit-learn
  - pycocotools
  - opencv
  - flake8
  - tqdm
  # - pip:
    # - pycocotools
    # - opencv-python